### ISSUE TITLE
 status-node err :panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lulei0215** [spacemeshos/cli-wallet#24]
Welcome to Spacemesh. Connected to api server at localhost:9092 (GRPC API 2.0). >> Insecure Connection. Use only with a local trusted server <<
> Network id: 29
> Max transactions per second: 16
> Layers per epoch: 288
> Layer duration: 300 seconds
> Current layer: 1951
> Current epoch: 6
> Genesis time: 2021-05-04 23:15:48 +0800 CST
Your console window is too small...$ status-node
> Version: v0.1.15
> Build: a0df2b8f87d05085182e7e2989d09901aca8dc3c
> API server: localhost:9092 (GRPC API 2.0). >> Insecure Connection. Use only with a local trusted server <<
> Synced: false
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9a63c8]

goroutine 1 [running]:
github.com/spacemeshos/CLIWallet/repl.(*repl).nodeInfo(0xc00049e240)
        /home/ll/go/src/awesomeProject/cli-wallet/repl/node_commands.go:27 +0x4e8
github.com/spacemeshos/CLIWallet/repl.(*repl).executor(0xc00049e240, 0xafaeb4, 0xb)
        /home/ll/go/src/awesomeProject/cli-wallet/repl/repl.go:191 +0x19c
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000475580)
        /home/ll/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.3/prompt.go:85 +0x7b0
github.com/spacemeshos/CLIWallet/repl.runPrompt(0xc0004a4010, 0xc0004a4020, 0xc000321e48, 0x18)
        /home/ll/go/src/awesomeProject/cli-wallet/repl/prompt.go:25 +0x110
github.com/spacemeshos/CLIWallet/repl.Start(0xbefda8, 0xc00041cb70)

**Comment by avive** [comment]
Need a bit more info here: what release of the go-sm node are you running? Is it one of the release binaries or a version that you have build yourself from source code? If from source code - from which commit did you build the node?

**Comment by lulei0215** [comment]
what do you mean =》I run the 0.1.32 version of the code on the horse，It's ok, right?

**Comment by lulei0215** [comment]
But isn’t the released version 0.1.15?

**Comment by lulei0215** [comment]
When will version 0. 2 come out
？

**Comment by avive** [comment]
The current testnet is netid=30. Please use the go-spacemesh and cliwallets releases for this network using the info in the github repos readmes, and let us know if the issue is still reproducible.

**Comment by avive** [comment]
Need to try to repro with most recent releases of smrepl and node
